services:
  redis: 
    image: redis:7.0-alpine 
    restart: unless-stopped
    ports: 
      - 6379:6379
    volumes:
      - redis-cache:/data:rw
    environment:
      - TZ=Europe/Paris
  mariadb: 
    image: mariadb:11.4
    restart: unless-stopped
    volumes: 
      - glpi-db:/var/lib/mysql:rw
    env_file: ./.env
    environment:
      - TZ=Europe/Paris
    ports: 
      - 3306:3306
  php: 
    build: php-fpm/.
    restart: unless-stopped
    volumes: 
      - glpi-root:/var/www/html/:rw
      - marketplace:/var/www/html/marketplace:rw
      - config:/etc/glpi/config/:rw
      - var-lib-glpi:/var/lib/glpi/:rw
      - ./php-fpm/conf.d:/usr/local/etc/php/conf.d:ro
    env_file: ./.env
    environment:
      - TZ=Europe/Paris
    depends_on: 
      - mariadb
    ports: 
      - "9000:9000"

  nginx: 
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes: 
      - glpi-root:/var/www/html/:rw
      - marketplace:/var/www/html/marketplace:rw
      - config:/etc/glpi/config/:rw
      - var-lib-glpi:/var/lib/glpi/:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    environment:
      - TZ=Europe/Paris
    ports: 
      - "80:80"
      - "443:443"
    depends_on: 
      - php

volumes: 
  glpi-root:
  var-lib-glpi:
  config:
  marketplace:
  glpi-db:
  redis-cache:
  
    