services:
  redis: 
    image: redis:7.0-alpine 
    restart: unless-stopped
    ports: 
      - 6379:6379
    volumes:
      - ./glpi/redis:/data:rw
  mariadb: 
    image: mariadb:11.4
    restart: unless-stopped
    volumes: 
      - ./glpi/mariadb:/var/lib/mysql:rw
    env_file: ./.env
    ports: 
      - 3306:3306
  php: 
    build: php-fpm/.
    restart: unless-stopped
    volumes: 
      - glpi-root:/var/www/html/:rw
      - ./glpi/glpi/marketplace:/var/www/html/marketplace:rw
      - ./glpi/glpi/files:/var/lib/glpi:rw
      - ./glpi/glpi/config:/etc/glpi/config/:rw
      - var-lib-glpi:/var/lib/glpi/:rw
      - ./php-fpm/conf.d:/usr/local/etc/php/conf.d:ro
    env_file: ./.env
    depends_on: 
      - mariadb
    ports: 
      - "9000:9000"

  nginx: 
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes: 
      - glpi-root:/var/www/html/:rw
      - ./glpi/glpi/marketplace:/var/www/html/marketplace:rw
      - ./glpi/glpi/files:/var/lib/glpi:rw
      - ./glpi/glpi/config:/etc/glpi/config/:rw
      - var-lib-glpi:/var/lib/glpi/:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports: 
      - "8080:8080"
    depends_on: 
      - php

volumes: 
  glpi-root:
  var-lib-glpi:
  
    